### ISSUE TITLE
由于物品材质导致的刷铁砧bug

### ISSUE THREAD

**Issue by JiangQiYan713** [GuizhanCraft/FastMachines#11]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.com)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/ybw0014/FastMachines/issues)，且没有找到相同的问题

### 问题描述

前提：世界规则为开启方块掉落
悬空方式快捷盔甲锻造台
掉落铁砧

### 复现步骤

https://github.com/GuizhanCraft/FastMachines/assets/91627081/e2f92b95-ef08-427a-ba20-4eb7591b84e7

### 预期行为

不会掉落铁砧 或者它不是一个铁砧材质

### 服务器日志

无

### 错误报告

无

### 服务端软件

Paper

### Minecraft 版本

1.20.2

### Slimefun版本

![%~ PRUMCLA7E5IJ%ZEE@ZOJ](https://github.com/GuizhanCraft/FastMachines/assets/91627081/28e22aec-ef0e-4b26-922b-ef9ebccdd6f3)

### 插件版本

1

**Comment by ybw0014** [comment]
00faaaaaeb8d0b47e6a4f7d79032bcffaee65875
