### ISSUE TITLE
没有任何配方

### ISSUE THREAD

**Issue by gyc123456-1** [GuizhanCraft/FastMachines#38]
### 检查项目

- [X] 你使用的是从鬼斩构建站（<https://builds.guizhanss.com>）或 Blob 构建站（https://blob.build/）下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/ybw0014/FastMachines/issues)，且没有找到相同的问题

### 问题描述

即使是正确的配方，底下也什么都不会显示

### 复现步骤

1.打开任意快捷机器
2.放入配方材料

### 预期行为

底下显示我要合成的东西

### 服务端软件

Paper

### Minecraft 版本

1.20.1

### Slimefun版本

Slimefun 运行的服务器环境:
Paper git-Paper-196 (MC: 1.20.1)
Slimefun 2023.10.20-release
Metrics-组件 #29
Java 17

由 StarWishsama 汉化
请不要将此版本信息截图到 Discord/Github 反馈 Bug
优先到汉化页面反馈

安装的附属插件: (35)
  Networks vBuild 85 (git 2e809b2)
  GuizhanLibPlugin vBuild 40 (git 98aa086)
  AureliumSkills vBeta 1.3.23
  FoxyMachines vBuild 26 (git cb02352)
  RelicsOfCthonia vBuild 8 (git 0763968)
  SlimefunOreChunks vBuild 1 zh-CN(ybw0014) (git 67879ed)
  FNAmplifications vBuild 14 (git a1fb89c)
  DynaTech vBuild 64 (git bec6023)
  InfinityExpansion vBuild 11 (git f9fe427)
  Supreme vBuild 16 (git d67997d)
  SFCalc vBuild 4 zh-CN(ybw0014) (git ca78ab1)
  ElectricSpawners vBuild 5 (git 6fa0de2)
  UltimateGenerators vBuild 9 RC-27(LittleQiu233) (git 453f245)
  BetterReactor vBuild 3 (git de00343)
  DeEnchantment v2.1.11
  WhatIsThis v5.3
  SlimyTreeTaps vBuild 2 zh-CN(ybw0014) (git 8a58b9f)
  MobCapturer vBuild 15 (git cc3a3c5)
  PrivateStorage vBuild 1 zh-CN(ybw0014) (git 7205ea3)
  SlimeTinker vBuild 49 (git 5712518)
  CMI v9.6.9.8
  FluffyMachines vBuild 30 (git 22b4c94)
  ItemsAdder v3.6.2c
  DyedBackpacks vBuild 3 (git d4e0e45)
  FastMachines vBuild 26 (git 4b445ca)
  Residence v5.1.4.1
  SlimefunWarfare vBuild 10 (git 1f8339a)
  HardcoreSlimefun v1.0
  EcoPower vBuild 1 zh-CN(ybw0014) (git eca8ab1)
  HotbarPets vBuild 3 zh-CN(ybw0014) (git 92415a4)
  ExoticGarden vBuild 17 (git 2a33c6d)
  SlimeGlue v1.0.2-b262a4a
  LiteXpansion vBuild 31 (git 4f03e6b)
  SimpleUtils vBuild 2 (git f774b8d)
  SlimeSec vBuild 1 zh-CN(SlimefunGuguProject) (git 2c0652c)

### 插件版本

Build 26 (git 4b445ca)

**Comment by ybw0014** [comment]
请提供日志

**Comment by gyc123456-1** [comment]
把粘液科技本体更新到最新就好了，但是还是要点下空白位置。。。
