### ISSUE TITLE
2 errors in FastMachine

### ISSUE THREAD

**Issue by hiiamken** [GuizhanCraft/FastMachines#40]
### Checklist

- [X] You are using official version downloaded from Blob Builds (https://blob.build/) or Guizhan Builds (<https://builds.guizhanss.com>)
- [X] You checked the checksum of the downloaded file, and confirmed that the file is complete
- [X] You did not modify the jar file
- [X] You searched existing issues, and could not find any existing bug report on this

### Description

The error in the video is that when you click craft, you lose the ingredients but no product
https://github.com/GuizhanCraft/FastMachines/assets/142149960/e1152673-d1bc-48af-b9a5-979e632b80a8

The second error is that craft products are not displayed even though they have enough ingredients
![image](https://github.com/GuizhanCraft/FastMachines/assets/142149960/497b4473-b1ee-460a-8f58-0e421d9f97ee)
![image](https://github.com/GuizhanCraft/FastMachines/assets/142149960/f447c525-2f80-4e9d-b523-d45c8237a6b6)

### Reproduction Steps

1. Put enough ingredients into the fastmachine
2. Nothing appears in the product slot

### Expected Behavior

1. The error in the video must include the product and the message "Insufficient ingredients" appears
2. The error in the 2 images should show the product box because the formula is correct

### Server Software

Paper

### Minecraft version

1.20.4

### Slimefun version

![image](https://github.com/GuizhanCraft/FastMachines/assets/142149960/8a83390d-420b-4e9a-9967-36234ffa2595)
![image](https://github.com/GuizhanCraft/FastMachines/assets/142149960/ff4a6732-3ad5-4ba2-b628-3fb0667d5022)
![image](https://github.com/GuizhanCraft/FastMachines/assets/142149960/a410e123-ffa9-458f-95d8-697d2ad6198e)

### Plugin version

FastMachines vDev - 15

**Comment by ybw0014** [comment]
please don't merge issues. provide more detailed reproduction steps (which item's ingredients, which machine)

**Comment by hiiamken** [comment]
Reproduction Steps
1. Put enough ingredients (in the picture) into the Fast Crafting Table
![image](https://github.com/GuizhanCraft/FastMachines/assets/142149960/bb7635dc-a78d-43fb-ac5f-a61126b65ba1)

2. Nothing appears in the product slot (Barrier)
![image](https://github.com/GuizhanCraft/FastMachines/assets/142149960/7332ab29-705b-4fb9-8247-040f18e80908)

**Comment by hiiamken** [comment]
The error in the video is that it shows the product but when you click "Craft", it loses the ingredients even though there is a message "Not enough ingredients"
![image](https://github.com/GuizhanCraft/FastMachines/assets/142149960/433a428e-79db-4d71-b899-9000d0d3cb77)

**Comment by hiiamken** [comment]
Same machine and same formula

**Comment by ybw0014** [comment]
electric ore grinder 2 can be crafted on my test server with fast enhanced crafting table. cannot reproduce this.
are there any errors in the console? are your diamond pickaxes completely new?

**Comment by hiiamken** [comment]
https://github.com/GuizhanCraft/FastMachines/assets/142149960/b93e257c-e96e-4b67-b9d5-f60dfae5791b

Network grabber can be crafted with SimpleWorkbench but cannot be crafted with enhanced crafting table

**Comment by hiiamken** [comment]
This error applies to all formulas
1. The output material is still displayed in the GUI even though the material has been removed
2. Smash the crafting table
3. If you place it again, you won't be able to craft anything anymore


https://github.com/GuizhanCraft/FastMachines/assets/142149960/7c39e103-d9a9-4f1c-b960-7c4bd5efb941

**Comment by hiiamken** [comment]
![image](https://github.com/GuizhanCraft/FastMachines/assets/142149960/56b88821-d538-487c-9668-d7668f53acbf)

https://mclo.gs/yG7GJgJ 

my lastest log
