### ISSUE TITLE
一大堆报错

### ISSUE THREAD

**Issue by hseermc** [GuizhanCraft/FastMachines#43]
### 检查项目

- [X] 你使用的是从鬼斩构建站（<https://builds.guizhanss.com>）或 Blob 构建站（https://blob.build/）下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/ybw0014/FastMachines/issues)，且没有找到相同的问题

### 问题描述

今天更了最新版本就这样了

### 复现步骤

![63d9270f09fdb0d0eac4d4ee9a07802d_720](https://github.com/GuizhanCraft/FastMachines/assets/143265074/b035b3bc-ad22-48df-ac27-e53bcd7ea712)
合成这玩意（具体还有没有毛病不确定，至少服务器里面的人合这玩意有报错

### 预期行为

正常用

### 错误报告

https://paste.guizhanss.net/ECVNS

### 服务端软件

Paper

### Minecraft 版本

1.20.4

### Slimefun版本

 Slimefun v35a49db-Beta

### 插件版本

Build 33 git 99dd8be

**Comment by hseermc** [comment]
必现，已经报了好多一模一样的报错

**Comment by ybw0014** [comment]
开启`debug`，然后发一份带debug的日志，需要看一下哪个配方出了问题

**Comment by hseermc** [comment]
emm...怎么开……

**Comment by hseermc** [comment]
debug是不是要重启才能开启啊……

**Comment by hseermc** [comment]
https://mclo.gs/q1x5eYf
里面夹了一坨SQL语句报错，就显得有点大（）
