### ISSUE TITLE
使用SlimefunRecipe修改配方后 该配方无法使用FastMachines的快速合成功能

### ISSUE THREAD

**Issue by CuteLittleSky** [GuizhanCraft/FastMachines#45]
### 检查项目

- [X] 你使用的是从鬼斩构建站（<https://builds.guizhanss.com>）或 Blob 构建站（https://blob.build/）下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/ybw0014/FastMachines/issues)，且没有找到相同的问题

### 问题描述

使用SlimefunRecipe修改配方后 该配方无法使用FastMachines的快速合成功能(无法识别到合成配方,已重启服务器)
已尝试让SlimefunRecipe在FastMachines前加载

### 复现步骤

![PixPin_2024-06-16_12-18-47](https://github.com/GuizhanCraft/FastMachines/assets/62592731/fc266dd5-4aab-490f-981c-374c62f3e414)

### 预期行为

使用SlimefunRecipe修改配方后可以识别到合成配方

### 服务端软件

Paper

### Minecraft 版本

1.20.4

### Slimefun版本

Slimefun 226af9b-Beta

### 插件版本

FastMachines-Build 36 (git c0097f4)

**Comment by ybw0014** [comment]
我看 SFR 是 enable 时加载的，让快捷机器后加载 SFR 就读取不到物品
