### ISSUE TITLE
1.21版本中即使设置了机器无需用电，但是还会需要电

### ISSUE THREAD

**Issue by hseermc** [GuizhanCraft/FastMachines#48]
### 检查项目

- [X] 你使用的是从鬼斩构建站（<https://builds.guizhanss.com>）或 Blob 构建站（<https://blob.build/>）下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/ybw0014/FastMachines/issues)，且没有找到相同的问题

### 问题描述

当  use-energy: false时，无法关闭消耗电力

### 复现步骤

1.服务器1.21版本
2.关闭消耗电力
3.使用快捷熔炉
4.无法使用

### 预期行为

无需耗电即可使用

### 服务端软件

Paper

### Minecraft 版本

1.21

### Slimefun版本

Leaves 1.21-12-ab8b5f9 (MC: 1.21)
Slimefun 14602eb-Insider
Metrics-组件 #29
Java 21

### 插件版本

build 39 git 9402791

**Comment by ybw0014** [comment]
关闭用电后，由于快捷机器都是电力机器，因此仍然会显示需要电力，但实际点击合成的时候并不会扣除电力（无论有无电力）

**Comment by ybw0014** [comment]
已在 [1e15fda](https://github.com/GuizhanCraft/FastMachines/commit/1e15fdaa2be6e0727e96157990ca74db3f80e600) 中优化
